//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assortment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assortment()
        {
            this.ordercompositions = new HashSet<ordercomposition>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Category { get; set; }
        public string Remains { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Manufacturer { get; set; }
        public string Descriprion { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual Category Category1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ordercomposition> ordercompositions { get; set; }
        public virtual Manufacturer Manufacturer1 { get; set; }
    }
}
