//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklad
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class SkladEntities : DbContext
    {
        private static SkladEntities _context;
        public SkladEntities()
            : base("name=SkladEntities")
        {
        }
        public static SkladEntities GetContext()
        {
            if (_context == null)
                _context = new SkladEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Assortment> Assortments { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<ordercomposition> ordercompositions { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<orderstatu> orderstatus { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Manufacturer> Manufacturers { get; set; }
    }
}
