//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklad
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordercomposition
    {
        public int Id { get; set; }
        public Nullable<int> Idorder { get; set; }
        public Nullable<int> IdAssortment { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Assortment Assortment { get; set; }
        public virtual Order Order { get; set; }
    }
}
